name: GitHub Actions Demo
on: [push]
jobs:
  test:
    name: running test for login 
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - run: |
              pip install -r POM/Clinician/requirements.txt
              cd POM/Clinician/Testcases
              pytest test_login.py


      
